..\..\devtools\bin\perl ..\..\..\bin\makedirhier.pl \ihvtest1\src\materialsystem
copy ..\..\materialsystem\stdshaders\BaseTimesMod2xEnvMap.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystemstdshaders\\Debug*.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\unlitgeneric*.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\unlitgeneric*.h \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\vertexlitgeneric*.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\wireframe.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\cmaterial*.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\cmaterial*.h \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\color*.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\color*.h \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\cshader.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\ctexture.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\imagepacker.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\materialsystem_global.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\shader.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\shadersystem.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\imaterial*.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\ishader*.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\imesh*.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\stdshaders\shaderapi.* \ihvtest1\src\materialsystem\
copy ..\..\public\materialsystem\materialsystem*.h \ihvtest1\src\materialsystem\
copy ..\..\public\shaderlib\cshader.h \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\itexture*.h \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\ctexture*.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\random.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\texturemanager.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\materialsystemihvtest.dsp \ihvtest1\src\materialsystem\materialsystem.dsp
copy ..\..\materialsystem\shaderdx8\*.vsh \ihvtest1\src\materialsystem\shaderdx8
..\..\devtools\bin\perl ..\..\..\..\bin\makedirhier.pl \ihvtest1\src\devtools\bin
copy ..\..\devtools\bin\perl.exe \ihvtest1\src\devtools\bin
copy ..\..\devtools\bin\perl*.dll \ihvtest1\src\devtools\bin
copy ..\..\devtools\bin\vsh_prep.pl \ihvtest1\src\devtools\bin
copy ..\..\devtools\bin\vsa.exe \ihvtest1\src\devtools\bin
mkdir \ihvtest1\src\materialsystem\shaderdx8\vshtmp
..\..\devtools\bin\perl ..\..\..\bin\makedirhier.pl \ihvtest1\src\public\materialsystem
copy ..\..\public\materialsystem\*.* \ihvtest1\src\public\materialsystem

